In [1]:
!python -V


Python 3.9.12


In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import seaborn as sb

In [3]:
# Question 1
# What's the version of NumPy that you installed?
np.__version__

'1.21.5'

In [4]:
# Question 2
# How many records are in the dataset?
df = pd.read_csv("data.csv")
df.shape[0]

11914

In [5]:
# Question 3
# Who are the most frequent car manufacturers (top-3) according to the dataset?

In [6]:
df['Make'].value_counts()[0:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

In [71]:
# Question 4
# What's the number of unique Audi car models in the dataset?
df[df.Make == 'Audi']['Model'].nunique()

34

In [72]:
df[df.Make == 'Audi']['Model'].unique()

array(['100', '200', '80', '90', 'A3', 'A4 allroad', 'A4', 'A5', 'A6',
       'A7', 'A8', 'allroad quattro', 'allroad', 'Cabriolet', 'Coupe',
       'Q3', 'Q5', 'Q7', 'R8', 'RS 4', 'RS 5', 'RS 6', 'RS 7', 'S3', 'S4',
       'S5', 'S6', 'S7', 'S8', 'SQ5', 'TT RS', 'TT', 'TTS', 'V8'],
      dtype=object)

In [8]:
# Question 5
# How many columns in the dataset have missing values?
df.isna().sum()[df.isna().sum()>0].count()

5

In [9]:
# Question 6
# Find the median value of "Engine Cylinders" column in the dataset.
df['Engine Cylinders'].median()

6.0

In [10]:
# Next, calculate the most frequent value of the same "Engine Cylinders".
df['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [11]:
# Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
# df['Engine Cylinders'].fillna(value = df['Engine Cylinders'].mode()).median()
df2 = df
df2['Engine Cylinders'] = df['Engine Cylinders'].fillna(4)

In [12]:
df2['Engine Cylinders'].median()

6.0

In [13]:
df2['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [14]:
df['Engine Cylinders'].value_counts()

4.0     4782
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [15]:
df2['Engine Cylinders'].value_counts()

4.0     4782
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [59]:
# Now, calculate the median value of "Engine Cylinders" once again.
# Has it changed?
# Hint: refer to existing mode and median functions to complete the task.

# A: No change. Reason: There are no NAs in column 'Engine Cylinders'

In [23]:
# Question 7
# Select all the "Lotus" cars from the dataset.
lotus = df[df.Make == 'Lotus']
lotus.describe()

Year   Engine HP  Engine Cylinders  Number of Doors  \
count    29.000000   29.000000         29.000000             29.0   
mean   2010.827586  275.965517          5.241379              2.0   
std       3.485367   64.131830          1.353703              0.0   
min    2002.000000  189.000000          4.000000              2.0   
25%    2009.000000  218.000000          4.000000              2.0   
50%    2011.000000  276.000000          6.000000              2.0   
75%    2013.000000  345.000000          6.000000              2.0   
max    2017.000000  400.000000          8.000000              2.0   

       highway MPG   city mpg  Popularity          MSRP  
count    29.000000  29.000000        29.0     29.000000  
mean     26.551724  18.758621       613.0  69188.275862  
std       3.822735   2.149006         0.0  14199.515666  
min      21.000000  14.000000       613.0  43995.000000  
25%      26.000000  18.000000       613.0  57950.000000  
50%      26.000000  20.000000       613.0  68300.000000  
75%      26.000000  20.000000       613.0  78600.000000  
max      39.000000  21.000000       613.0  93225.000000

In [24]:
# Select only columns "Engine HP", "Engine Cylinders".
lotus2 = lotus[['Engine HP', 'Engine Cylinders']]

In [26]:
# Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
lotus3 = lotus2.drop_duplicates()
lotus3.shape

(9, 2)

In [29]:
# Get the underlying NumPy array. Let's call it X.
X = lotus3.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [53]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
T = np.transpose(X)
T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [65]:
XTX = np.matmul(T, X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [66]:
# Invert XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [67]:
# Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [68]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = np.matmul( np.matmul(XTX_inv, T), y)
w

array([  4.59494481, -63.56432501])

In [70]:
# What's the value of the first element of w?
w[0]

4.594944810094579

In [ ]:
# A: 4.594944810094579